stages:
  - build
  - test
  - deploy
  
services:
    - docker:dind

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  before_script:

    - apt-get update && apt-get install -y curl

    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - chmod +x /usr/local/bin/docker-compose
  script:
    - echo "BUILD PHASE INITIATED"
    - docker-compose build
    - docker ps
    - echo "BUILD SUCCESSFUL"


test:
  stage: test
  services:
    - docker:dind
  script:
    - echo "Testing"


deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
    - echo "DEPLOYMENT SUCCESSFUL"
  only:
    - project
