image: docker:latest
stages:
  - build
  - test
  - deploy
  
services:
    - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - echo "BUILD PHASE INITIATED"
    - docker-compose build
    - docker ps
    - echo "BUILD SUCCESSFUL"


test:
  stage: test
  services:
    - docker:dind
  script:
    - echo "Testing"


deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
    - echo "DEPLOYMENT SUCCESSFUL"
  only:
    - project
