image: docker:latest
stages:
  - build
  - test
  - deploy
  
services:
  - name: docker:dind
    alias: docker

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - echo "BUILD PHASE INITIATED"
    - docker-compose build
    - docker ps
    - echo "BUILD SUCCESSFUL"


test:
  stage: test
  services:
    - docker:dind
  script:
    - echo "Test starting"
    - apk add --no-cache nodejs npm 
    - docker-compose down || true
    - docker-compose up -d
    - npm install -g mocha node-fetch assert
    - mocha tests/service1-tests.js
    - docker-compose down


deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
    - echo "DEPLOYMENT SUCCESSFUL"
  only:
    - project
