image: docker:latest
stages:
  - build
  - test
  - deploy
  
services:
  - name: docker:dind
    alias: docker

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - echo "BUILD PHASE INITIATED"
    - docker-compose build
    - docker ps
    - echo "BUILD SUCCESSFUL"


test:
  stage: test
  script:
    - docker-compose down || true
    - docker-compose up --build -d
    - docker-compose run tests npm test   
    - docker-compose down


deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
    - echo "DEPLOYMENT SUCCESSFUL"
  only:
    - project
