stages:
  - build
  - test
  - deploy
  
services:
    - docker:dind

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - echo "BUILD PHASE INITIATED"
    - docker-compose build
    - echo "BUILD SUCCESSFUL"


test:
  stage: test
  services:
    - docker:dind
  script:
    - echo "Testing"


deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
    - echo "DEPLOYMENT SUCCESSFUL"
  only:
    - project
