
services:

  service1:
    build: ./Service1
    deploy:
      replicas: 3
    networks:
      - service-bridge
      - loadbalancing

  service2:
    build: ./Service2
    networks:
      - service-bridge

  shutdown-service:
    build: ./shutdown-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - loadbalancing
    restart: "no"
    container_name: shutdown-service

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8198:8198"
    networks:
      - loadbalancing
    depends_on:
      - service1
      - shutdown-service
  apigateway:
    build: ./apigateway
    ports:
      - "8197:8197"
    depends_on:
      - service1
    networks:
      - loadbalancing
  tests:
    build: ./tests
    container_name: tests
    networks:
      - loadbalancing
    depends_on:
      - nginx


networks:
  service-bridge:
    driver: bridge
  loadbalancing:
    driver: bridge