version: '3'
services:

  service1:
    build: ./service1
    deploy:
      replicas: 3
    networks:
      - service-bridge
      - loadbalancing

  service2:
    build: ./service2
    networks:
      - service-bridge

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8198:8198"
    networks:
      - loadbalancing
    depends_on:
      - service1

networks:
  service-bridge:
    driver: bridge
  loadbalancing:
    driver: bridge