version: '3'
services:
  service1:
    build: ./service1
    ports:
      - "8199:8199"
    networks:
      - service-bridge

  service2:
    build: ./service2
    networks:
      - service-bridge

networks:
  service-bridge:
    driver: bridge